helmDefaults:
  timeout: 300
  createNamespace: true

repositories:
- name: stable
  url: https://charts.helm.sh/stable

releases:
- name: opa
  chart: stable/opa
  namespace: opa
  values:
  - opa-chart-values.yaml
