apiVersion: apps/v1
kind: Deployment
metadata:
  name: ydf-app-demo-stage
  namespace: qa
  labels:
    banana: lala
    app: alla
    environment: qa
    costCenter: lala
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ydf-app-demo-stage
      app.kubernetes.io/name: ydf-app-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ydf-app-demo-stage
        app.kubernetes.io/name: ydf-app-demo
    spec:
      containers:
      - image: nullck/circle_helm_test
        imagePullPolicy: IfNotPresent
        name: ydf-app-demo
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 80Mi
